server:
  port: 5555

spring:
  application:
    name: admin-server
  boot:
    admin:
      ui:
        title: Admin Server

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    show-details: always