
spring:
  application:
    name: flight-service


  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/flight
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver
server:
  port: 8886

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  health:
    show-details: always
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      getPatientInstance:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 3s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1.0



#      defaultZone: http://host.docker.internal:8762/eureka
#  instance:
#    prefer-ip-address: true
